[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
askama = "0.14"
tower-http = { version = "0.5", features = ["fs"] }
serde = { version = "1", features = ["derive"] }
